module.exports = {
  cherryBounce:
    'CAACAgIAAxkBAANKXogv4knCS-h3ljVtVbQz5X0iRP8AAgUAA8A2TxP5al-agmtNdRgE',
  cherryWink:
    'CAACAgIAAxkBAAIBHl60Xs0IIWBh2NzFEDQdHpwRTRJAAAINAAPANk8TpPnh9NR4jVMZBA',
  gooseShock:
    'CAACAgIAAxkBAANAXohGAAFk8OOXNwaDXiiGmHUVpCP7AAJCAANSiZEjg8hUYzO75FkYBA',
  porgWhat:
    'CAACAgIAAxkBAAIBF160XddARcYP19bAPSlXyhSg6P8rAAJABQACa8TKCvqec0RBVewxGQQ',
}
